apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  {{- $files := .Files }}
  {{- range tuple "files/bigfile.txt"}}
  {{ . }}: |-
        {{ $files.Get . }}
  {{- end }}
